version: '3.8'

services:
  app-elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}"
    volumes:
      - ./app/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./app/elasticsearch/script/add-demo-data:/usr/local/bin/add-demo-data
    expose:
      - 9200
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx2048m"
  app-metricbeat:
    image: "docker.elastic.co/beats/metricbeat:${METRICBEAT_VERSION}"
    volumes:
      - ./app/metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./app/metricbeat/config/modules.d/elasticsearch-xpack.yml:/usr/share/metricbeat/modules.d/elasticsearch-xpack.yml
    depends_on:
      - app-elasticsearch
      - monitoring-elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx2048m"

  monitoring-elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}"
    volumes:
      - ./monitoring/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - 9200
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx2048m"
  monitoring-kibana:
    image: "docker.elastic.co/kibana/kibana:${KIBANA_VERSION}"
    volumes:
      - ./monitoring/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - monitoring-elasticsearch
    expose:
      - 5601
    ports:
      - "5601:5601"
