metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts: ["http://monitoring-elasticsearch:9200"]

setup.kibana:
  host: "monitoring-kibana:5601"
